### PR TITLE
plugin installer to 0.2.0

### PR DESCRIPTION
**Pull request by daviduss2**
ready for roundcube 1.4.9

### CODE REVIEW

**Comment by strobilomyces** [comment]
First, thanks to everyone involved for this plugin. Is there anything that's kept this from being merged? Roundcube is now at 1.4.10 and this is still needed. Thanks again.

**Comment by daviduss2** [comment]
no, all other is fine

**Comment by GreenDragonTavern** [comment]
Thanks to all for this RC Plugin. Couldn't find another place to comment about this, but in case anyone else uses latest MariaDB, here is SQL that worked for me;

CREATE TABLE IF NOT EXISTS auth_tokens (
    `token` varchar(128) NOT NULL,
    `expires` datetime NOT NULL,
    `user_id` int unsigned NOT NULL,
    `user_name` varchar(128) NOT NULL,
    `user_pass` varchar(128) NOT NULL,
    `host` varchar(255) NOT NULL,
	PRIMARY KEY (`token`),
	CONSTRAINT `auth_tokens_ibfk_1` FOREIGN KEY (`user_id`)
	REFERENCES users(`user_id`) ON DELETE CASCADE
) /*!40000 ENGINE=INNODB */ /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */;

CREATE INDEX `user_id_fk_auth_tokens` ON auth_tokens (`user_id`);

REPLACE INTO `system` VALUES ('tx-persistent-login-version', '2020080200');

**Comment by chethutth96** [comment]
i have installed this plugin but am getting syntax error in the database initialization step i am using currently postgres db, i have taken .sql  below mentioned
 `/*
 * Roundcube Persistent Login Schema
 *
 * @author Gene Hawkins <texxasrulez@yahoo.com>
 *
 * @licence GNU AGPL
 */

CREATE TABLE IF NOT EXISTS auth_tokens (
    token varchar(128) NOT NULL,
    expires timestamp(0) NOT NULL,
    user_id int check (user_id > 0) NOT NULL,
    user_name varchar(128) NOT NULL,
    user_pass varchar(128) NOT NULL,
	host varchar(255) NOT NULL
   ,
	PRIMARY KEY (token),
	CONSTRAINT auth_tokens_ibfk_1 FOREIGN KEY (user_id)
	REFERENCES users(user_id) ON DELETE CASCADE
) /*!40000 ENGINE=INNODB */ /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */;

CREATE INDEX user_id_fk_auth_tokens ON auth_tokens (user_id);

REPLACE INTO `system` (name, value) SELECT ('tx-persistent-login-version', '2020080200');`

my error is 
`ERROR:  syntax error at or near "REPLACE"
LINE 1: REPLACE INTO `system` (name, value) SELECT ('tx-persistent-l...
        ^`
can any one please help me

**Comment by dbrossard** [comment]
Can we please get this merged? Without this it cannot be installed with composer:
` Problem 1
    - Root composer.json requires texxasrulez/persistent_login >=1.0.2 -> satisfiable by texxasrulez/persistent_login[1.0.2].
    - texxasrulez/persistent_login 1.0.2 requires roundcube/plugin-installer ~0.1.6 -> found roundcube/plugin-installer[0.1.6, ..., 0.1.10] but it conflicts with your root composer.json require (>=0.2.0).
`

**Pull request merged**
